### ISSUE TITLE
Handwrite API is not working

### ISSUE THREAD

**Issue by RSR-TG-Info** [Single-Developers/API#2]
**Error:**

Traceback (most recent call last):
2022-03-13T05:32:14.119159+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-03-13T05:32:14.119159+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-03-13T05:32:14.119159+00:00 app[worker.1]:   File "/app/MashaRoBot/modules/kutziak.py", line 21, in hwrite
2022-03-13T05:32:14.119160+00:00 app[worker.1]:     hmm = requests.post('https://api.single-developers.software/write', headers={'Content-Type': 'application/json'}, json={"text":f"{text}"}).history[1].url
2022-03-13T05:32:14.119161+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/requests/api.py", line 117, in post
2022-03-13T05:32:14.119161+00:00 app[worker.1]:     return request('post', url, data=data, json=json, **kwargs)
2022-03-13T05:32:14.119161+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/requests/api.py", line 61, in request
2022-03-13T05:32:14.119162+00:00 app[worker.1]:     return session.request(method=method, url=url, **kwargs)
2022-03-13T05:32:14.119162+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
2022-03-13T05:32:14.119162+00:00 app[worker.1]:     resp = self.send(prep, **send_kwargs)
2022-03-13T05:32:14.119163+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
2022-03-13T05:32:14.119163+00:00 app[worker.1]:     r = adapter.send(request, **kwargs)
2022-03-13T05:32:14.119164+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
2022-03-13T05:32:14.119164+00:00 app[worker.1]:     raise SSLError(e, request=request)
2022-03-13T05:32:14.119165+00:00 app[worker.1]: requests.exceptions.SSLError: HTTPSConnectionPool(host='api.single-developers.software', port=443): Max retries exceeded with url: /write (Caused by SSLError(CertificateError("hostname 'api.single-developers.software' doesn't match '*.up.railway.app'")))

**Comment by Malith-Rukshan** [comment]
![image](https://user-images.githubusercontent.com/85282650/158053807-6aa77500-fad7-465d-a211-8173b65696bc.png)

🚧 You Must Change API Domain Name : - `single-developers.up.railway.app`

**Comment by RSR-TG-Info** [comment]
**What my mistakes?**

@pbot.on_message(filters.command("hwrite", prefixes=["/", "!"]))
async def hwrite(client, message):
    text = get_text(message)
    if not get_text(message):
        await message.reply_text("siam tur thu i dah tel lo")
        return
    txt = await edit_or_reply(message, "`Siam mek...`")
    hmm = requests.post('https://single-developers.up.railway.app', headers={'Content-Type': 'application/json'}, json={"text":f"{text}"}).history[1].url
    if message.reply_to_message:
        await client.send_chat_action(message.chat.id, "upload_photo")
        await client.send_photo(
            message.chat.id,
            photo=hmm,
            reply_to_message_id=message.reply_to_message.message_id,
            parse_mode=ParseMode.HTML
        )
    else:
        await client.send_chat_action(message.chat.id, "upload_photo")
        await client.send_photo(
            message.chat.id,
            photo=hmm,
            reply_to_message_id=message.message_id,
            parse_mode=ParseMode.HTML
        )

**Comment by Hasith035** [comment]
Are Logo Maker and Wallpaper APIs working ???

**Comment by Hasith035** [comment]
You should change **"https://api.single-developers.software/write"** to **"https://api.single-developers.up.railway.app/write"**

**Comment by Malith-Rukshan** [comment]
![image](https://user-images.githubusercontent.com/85282650/164389243-4386a869-8c64-4167-906b-c812738ba64f.png)
✨ Change Request URL to : `https://single-developers.up.railway.app/write`
****
![image](https://user-images.githubusercontent.com/85282650/164389907-b822a0a7-25a5-4b3b-863e-c3ca2efea46e.png)
👆 Like This  : )
